### ISSUE TITLE
storage tutorial improvements

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/scicomp-docs#123]
The storage tutorial could use some better exercises, less technical and abstract.  We were thinking that it could be more about lightweight testing of real code to understand how much i/o it does.

- benchmark a program, e.g. import `python -e file-c 'import keras'`
- strace is simplest
- understand i/o of a file, `strace -e file`
- ... ?

Some of this could be combined with the profiling page.

**Comment by tpfau** [comment]
I think some of this has been done but probably can still be improved
