### ISSUE TITLE
publications where RSEs should be a coauthor

### ISSUE THREAD

**Issue by eglerean** [AaltoSciComp/scicomp-docs#162]
I think we should add to page

https://github.com/AaltoSciComp/scicomp-docs/blob/master/rse/become-a-rse.rst

the possibility of being a coauthor, not as a "carrot and stick" promise but to be ethical and follow TENK ethical guidelines on coauthorship:

https://www.tenk.fi/sites/tenk.fi/files/HTK_ohje_2012.pdf
especially page 30:

_Before beginning the research or recruiting the
researchers, all parties within the research project or
team (the employer, the principal investigator, and
the team members) agree on the researchers’ rights,
responsibilities, and obligations, principles concerning
authorship, and questions concerning archiving and
accessing the data. These agreements may be further
specified during the course of the research._

A good rule of thumb for a "significant" contribution is:

**Authorship connotes at least two of the following contributions:
1. Initial idea
2. Field and/or lab work/data collection
3. Data analysis/images
4. Write/edit article**

It could be agreed in advance with the PI. In general it is important to discuss this always before any project to avoid unfortunate (rare) situations where the RSE might invent/discover something groundbreaking, but is then not acknowledged in the final work.

How do they do in other RSE sites? Let's discuss?

**Comment by rkdarst** [comment]
I was going to make a path on scicomp, `/rse/procedures/` (ideas about a better name?), to start collecting these kind of procedures once you are already in or using the system.

I made the mistake of putting mystarting info in this private readme, which I will move to this repository shortly: https://version.aalto.fi/gitlab/AaltoRSE/rse-projects
Any objections to that?

**Comment by eglerean** [comment]
no objections! Actually it makes perfect sense that that page is public and lives here on scicomp.aalto while the actual requests + project management can stay "private" under version.aalto.fi.

**Comment by rkdarst** [comment]
Mentioned in rse/how-we-work.rst (briefly).
