### ISSUE TITLE
duplicate content in the "triton/usage/faq.rst"

### ISSUE THREAD

**Issue by woodwm** [AaltoSciComp/scicomp-docs#246]
Hi, I find that there are many duplicate content in the file [triton/usage/faq.rst](https://github.com/AaltoSciComp/scicomp-docs/blob/master/triton/usage/faq.rst) maybe starting from [While copying to $WRKDIR with rsync or cp I'm getting 'Disk quota exceeded' error, though my quota is fine.](https://github.com/AaltoSciComp/scicomp-docs/blob/master/triton/usage/faq.rst#while-copying-to-wrkdir-with-rsync-or-cp-im-getting-disk-quota-exceeded-error-though-my-quota-is-fine-1)

**Comment by tpfau** [comment]
This should probably be sorted in some way not "newest -> oldest" but based on topics.

**Comment by woodwm** [comment]
Great to see the first reply after almost ten months. I cannot see any topics here. No reason for replication.
