### ISSUE TITLE
Missing aalto version pdf

### ISSUE THREAD

**Issue by manuelhaussmann** [AaltoSciComp/scicomp-docs#448]
The Aalto gitlab page: https://scicomp.aalto.fi/aalto/git/#aalto-gitlab-service is referencing a pdf file that seems to have moved/no longer exists

> The Aalto instructions can be found here, and general gitlab help here.

where here points to: https://version.aalto.fi/docs/aalto_version_quickstart_guide.pdf

**Comment by rkdarst** [comment]
thanks!
