### ISSUE TITLE
Things remaining to be migrated from department's pages

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/scicomp-docs#6]
- NBE: page: Firefox and Thunderbird local profiles on Aalto Linux
- NBE: Remote+windows+connection (adobe stuff, plus now graphical program examlpe)
- PHYS: generally a lot of stuff that could be useful, need to come back to it.

**Comment by jabl** [comment]
Condor instructions.

**Comment by rkdarst** [comment]
- CS: printing, some of it
- Maybe some of virtual servers
- Maybe some of video conferencing, but only if it's similar in other departments
- web pages (currently hidden in storage/linux)

**Comment by rkdarst** [comment]
Condor from HTCondor wiki space imported to `aalto/htcondor.rst`.  Please edit if needed.

**Comment by rkdarst** [comment]
PHYS has the best printing pages, but most is about self-managed printers.  I'm not sure how much of this overlaps with other departments?  CS has some generic stuff on SecurePrint.

Can CS virtual server info be made sort-of generic?

**Comment by mhakala** [comment]
Hmm, the local profiles are no longer in use. Also remote connections include hostnames. I'd leave those out, that is, leave something to local wiki.

**Comment by rkdarst** [comment]
About what to include.  I'm a fan of Kerckhoffs' principle and openness, but the decision needs to be informed.  If something can be found already publicly, it's not helpful to make it more confusing to use the documentation. 

Already, Aalto-level login servers are available on public Aalto sites.  All IPs are continually under attack for SSH servers anyway, so keeping Aalto-managed shell servers secret seems pointless. Internal Triton hostnames are already public in SCIP slides, it seems (at least login).

The main other thing I have right now is SMB addresses for mounting stuff.  These are only accessible from internal Aalto networks anyway.

Maybe a good compromise is: things that are accessible from public internet have to have agreement with owner.  Things only from networks that require authentication first can be listed if it's a high-profile service anyway.
