### ISSUE TITLE
page aalto/git: external user form changed

### ISSUE THREAD

**Issue by IlariLahteenmaki** [AaltoSciComp/scicomp-docs#665]
Hi, form to request accounts for external users has been changed to this: https://selfservice.esupport.aalto.fi/ssc/app%23/order/2068/ 
More information at: https://www.aalto.fi/en/services/aalto-version-how-to-apply-an-account-for-an-external-user

Just a simple link fix for your great page about the service.

Yours,
Ilari

**Comment by rkdarst** [comment]
updated (plus a few more things), thanks!
